# Generated by Django 2.1.1 on 2019-08-03 12:12

import a.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('orgImg', models.ImageField(blank=True, default=None, null=True, upload_to=a.models.save_orginalpic)),
                ('heatMap', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('predict', models.CharField(blank=True, default='true', max_length=10, null=True)),
                ('withModel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Models')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
