# Generated by Django 2.1.1 on 2019-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='orgImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='orginal/'),
        ),
    ]
